language: node_js
node_js:
  - '14.15.0'
script:
  - node common/scripts/install-run-rush.js rebuild -p 3 -i vueapp -v
sudo: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  target-branch: gh-pages # deploy target branch
  verbose: true
  on:
    branch: master
